QT += widgets serialport

TARGET = mercurytestutility
TEMPLATE = app
CONFIG += c++11

#GIT_VERSION = $$system( git describe --always --tags )

GIT_VERSION = 1.4.0
DEFINES += GIT_VERSION=\\\"$$GIT_VERSION\\\"
VERSION = $$GIT_VERSION
win32
{
    VERSION ~= s/-\d+-g[a-f0-9]{6,}//
}

RC_ICONS = icons/kirintec_logo.ico

HEADERS = \  
    gui/inc/testequipmentdialog.hpp \
    gui/inc/mainwindow.hpp \
    testequipment/inc/visaresource.hpp \
    testequipment/inc/visaspectrumanalyser.hpp \
    gui/inc/tedetailswidget.hpp \
    common/inc/settings.hpp \
    testequipment/inc/testequipment.hpp \
    testequipment/inc/dummyspectrumanalyser.hpp \
    testequipment/inc/spectrumanalyser.hpp \
    testequipment/inc/testequipmentfactory.hpp \
    testequipment/inc/dummytestequipmentfactory.hpp \
    testequipment/inc/visatestequipmentfactory.hpp \
    testequipment/inc/powermeter.hpp \
    testequipment/inc/signalgenerator.hpp \
    testequipment/inc/dummypowermeter.hpp \
    testequipment/inc/dummysignalgenerator.hpp \
    testequipment/inc/visapowermeter.hpp \
    testequipment/inc/visasignalgenerator.hpp \
    testequipment/inc/visatestequipment.hpp \
    gui/inc/equipmentwidget.hpp \
    gui/inc/equipmenttreewidget.hpp \
    gui/inc/tetreewidgetitem.hpp \
    testequipment/inc/testequipmentstore.hpp \
    gui/inc/testwidget.hpp \
    gui/inc/testtreewidget.hpp \
    gui/inc/progresswidget.hpp \
    common/inc/convert.hpp \
    gui/inc/serialportsdialog.hpp \
    testjig/inc/rfswitchmatrix.hpp \
    testjig/inc/testjigdetails.hpp \
    testjig/inc/testjig.hpp \
    testjig/inc/mercurytestjig1.hpp \
    testsuite/inc/testcase.hpp \
    gui/inc/actiondialog.hpp \
    common/inc/logging.hpp \
    gui/inc/testtreewidgetitem.hpp \
    gui/inc/dutdialog.hpp \
    testsuite/inc/testcasemembraneleds.hpp \
    testsuite/inc/testcasemembranebuttons.hpp \
    gui/inc/messagedialog.hpp \
    gui/inc/manualtestdialog.hpp \
    testjig/inc/dutpowercontrol.hpp \
    comms/inc/directserialcomms.hpp \
    comms/inc/serialcomms.hpp \
    comms/inc/registercomms.hpp \
    comms/inc/sourceboardcomms.hpp \
    dut/inc/deviceundertest.hpp \
    dut/inc/sourceboard.hpp \
    testsuite/inc/testcasesourceboard.hpp \
    testsuite/inc/testcasemembrane.hpp \
    dut/inc/membrane.hpp \
    gui/inc/duttreewidgetitem.hpp \
    comms/inc/registercontrol.hpp \
    hardware/inc/gpio.hpp \
    testsuite/inc/testcasesourceboardgpio.hpp \
    hardware/inc/gpiotester.hpp \
    testsuite/inc/tester.hpp \
    testsuite/inc/testcasesourceboardbit.hpp \
    testsuite/inc/testcasesourceboardtamper.hpp \
    testsuite/inc/testcasesourceboardcontrol.hpp \
    testsuite/inc/testcasesourceboarddockctrl.hpp \
    hardware/inc/sourceboardrfcontrol.hpp \
    testsuite/inc/testcasesourceboardsynth.hpp \
    testsuite/inc/testcasesourceboarddcpower.hpp \
    testsuite/inc/testcasesourceboardddspower.hpp \
    testsuite/inc/testcasesourceboardddsfrequency.hpp \
    testjig/inc/cablecal.hpp \
    common/inc/calibration.hpp \
    testjig/inc/irfjig.hpp \
    gui/inc/griddialog.hpp \
    testsuite/inc/testcasesourceboardddscalibration.hpp \
    dut/inc/sourceboardbit.hpp \
    hardware/inc/registeradc.hpp \
    hardware/inc/registergpio.hpp \
    testjig/inc/testjigfactory.hpp \
    testjig/inc/testharness.hpp \
    testsuite/inc/testcasesourceboardddscurrent.hpp \
    dut/inc/ddscalfile.hpp \
    gui/inc/delayprogressdialog.hpp \
    testsuite/inc/testcasepowermonitor.hpp \
    dut/inc/powermonitor.hpp \
    testjig/inc/testharnesssourceboard.hpp \
    testjig/inc/testharnesspowermonitor.hpp \
    testsuite/inc/testcasepowermonitordcpower.hpp \
    testsuite/inc/testcasepowermonitorinsertionloss.hpp \
    testjig/inc/rfpath.hpp \
    hardware/inc/rfband.hpp \
    gui/inc/modaldialog.hpp \
    testsuite/inc/testcasepowermonitornorf.hpp \
    testsuite/inc/testcasepowermonitordirectivity.hpp \
    testjig/inc/testharnessmembrane.hpp \
    hardware/inc/port.hpp \
    testsuite/inc/testcasesourceboardpactrlmonitor.hpp \
    testsuite/inc/testcasesourceboarddaughter.hpp \
    testsuite/inc/testcasemidbandsourcemodule.hpp \
    testsuite/inc/testcasemidbandsourcemoduleid.hpp \
    testsuite/inc/testcasemidbandsourcemoduleportsel.hpp \
    testsuite/inc/testcasemidbandsourcemoduleatt.hpp \
    testsuite/inc/testcasemidbandsourcemodulerfpath.hpp \
    testsuite/inc/testcasemidbandsourcemoduledcpower.hpp \
    testsuite/inc/testcasemidbandsourcemoduleassy.hpp \
    gui/inc/cablecaldialog.hpp \
    testjig/inc/testjigcablecal.hpp \
    common/inc/calibrationstatus.hpp \
    gui/inc/testjigtreewidgetitem.hpp \
    dut/inc/psumodule.hpp \
    testsuite/inc/testcasepsumodule.hpp \
    testsuite/inc/testcasepsumoduleprogmicro.hpp \
    testsuite/inc/testcasepsumodulecontrolport.hpp \
    testsuite/inc/testcasepsumoduledcoutput.hpp \
    testsuite/inc/testcasepsumodulebit.hpp \
    testsuite/inc/testcasepsumodulethermalsensors.hpp \
    testsuite/inc/testcasepsumodulefans.hpp \
    testsuite/inc/testcasepsumodulepacontrol.hpp \
    dut/inc/dockcontroller.hpp \
    testjig/inc/testharnesspsumodule.hpp \
    testjig/inc/testharnessdockcontroller.hpp \
    testsuite/inc/testcasedockcontroller.hpp \
    testsuite/inc/testcasepsumoduledcinput.hpp \
    testsuite/inc/testcasedockcontrollerprogfpga.hpp \
    testsuite/inc/testcasedockcontrollerdcpower.hpp \
    testsuite/inc/testcasedockcontrollerbit.hpp \
    testsuite/inc/testcasedockcontrollercontrolport.hpp \
    testsuite/inc/testcasedockcontrollerpactrlmonitor.hpp \
    testsuite/inc/testcasedockcontrollergps.hpp \
    comms/inc/psucomms.hpp \
    testsuite/inc/testcasesourceboardfileloader.hpp \
    testsuite/inc/testcasesourceboardflashbootloader.hpp \
    hardware/inc/flashmagic.hpp \
    comms/xmodem/inc/crc16.h \
    comms/xmodem/inc/xmodemwrapper.hpp \
    gui/inc/fileselectdialog.hpp \
    comms/inc/dockcontrollercomms.hpp \
    hardware/inc/pacontrolmonitor.hpp \
    testjig/inc/pacontrolmonitortest.hpp \
    testsuite/inc/testcasedockcontrollereeprom.hpp \
    testsuite/inc/testcasedockcontrollerinterfaceid.hpp \
    testsuite/inc/testcasesourceboardappboot.hpp \
    hardware/inc/powermonitoradc.hpp \
    dut/inc/highbandsourcemodule.hpp \
    dut/inc/daughtermodule.hpp \
    hardware/inc/jlink.hpp \
    testsuite/inc/testcasesourceboardflashapp.hpp \
    testsuite/inc/testcasesourceboardstoreDdsfile.hpp \
    gui/inc/sanitycheckdialog.hpp \
    testjig/inc/sanitycheckcal.hpp \
    testsuite/inc/testcasesourceboardddscalcheck.hpp \
    common/inc/assyrevision.hpp \
    dut/inc/ctsboard.hpp \
    testjig/inc/testharnessctsboard.hpp \
    testsuite/inc/testcasectsboard.hpp \
    testsuite/inc/testcasectsboardflashfirmware.hpp \
    testsuite/inc/testcasectsboarddcpower.hpp \
    comms/inc/ctsboardcomms.hpp \
    testsuite/inc/testcasectsboardbit.hpp \
    testsuite/inc/testcasectsboardtamper.hpp \
    testsuite/inc/testcasectsboardsetserialnumber.hpp \
    testsuite/inc/testcasectsboardpreselectorbandwidth.hpp \
    testsuite/inc/testcasectsboardifbandwidth.hpp \
    testsuite/inc/ctstestband.hpp \
    testsuite/inc/testcasectsboardrfbandwidth.hpp \
    testsuite/inc/testcasectsboarddynamicrange.hpp \
    testsuite/inc/testcasectsboardbatterycharger.hpp \
    testsuite/inc/testcasectsboardusbserialport.hpp \
    testsuite/inc/testcasectsboardmembraneinterface.hpp \
    testsuite/inc/testcasectsboardgetversion.hpp
SOURCES =   gui/src/main.cpp \  
    gui/src/testequipmentdialog.cpp \
    gui/src/mainwindow.cpp \
    testequipment/src/visaresource.cpp \
    testequipment/src/visaspectrumanalyser.cpp \
    gui/src/tedetailswidget.cpp \
    common/src/settings.cpp \
    testequipment/src/testequipment.cpp \
    testequipment/src/dummyspectrumanalyser.cpp \
    testequipment/src/testequipmentfactory.cpp \
    testequipment/src/dummytestequipmentfactory.cpp \
    testequipment/src/visatestequipmentfactory.cpp \
    testequipment/src/dummypowermeter.cpp \
    testequipment/src/dummysignalgenerator.cpp \
    testequipment/src/visapowermeter.cpp \
    testequipment/src/visasignalgenerator.cpp \
    testequipment/src/visatestequipment.cpp \
    gui/src/equipmenttreewidget.cpp \
    gui/src/tetreewidgetitem.cpp \
    testequipment/src/testequipmentstore.cpp \
    gui/src/equipmentwidget.cpp \
    gui/src/testwidget.cpp \
    gui/src/testtreewidget.cpp \
    gui/src/progresswidget.cpp \
    common/src/convert.cpp \
    gui/src/serialportsdialog.cpp \
    testjig/src/rfswitchmatrix.cpp \
    testjig/src/testjigdetails.cpp \
    testjig/src/testjig.cpp \
    testjig/src/mercurytestjig1.cpp \
    testsuite/src/testcase.cpp \
    gui/src/actiondialog.cpp \
    common/src/logging.cpp \
    gui/src/testtreewidgetitem.cpp \
    gui/src/dutdialog.cpp \
    testsuite/src/testcasemembraneleds.cpp \
    testsuite/src/testcasemembranebuttons.cpp \
    gui/src/messagedialog.cpp \
    gui/src/manualtestdialog.cpp \
    testjig/src/dutpowercontrol.cpp \
    comms/src/registercomms.cpp \
    comms/src/directserialcomms.cpp \
    comms/src/serialcomms.cpp \
    comms/src/sourceboardcomms.cpp \
    dut/src/sourceboard.cpp \
    dut/src/deviceundertest.cpp \
    testsuite/src/testcasesourceboard.cpp \
    testsuite/src/testcasemembrane.cpp \
    dut/src/membrane.cpp \
    gui/src/duttreewidgetitem.cpp \
    comms/src/registercontrol.cpp \
    testsuite/src/testcasesourceboardgpio.cpp \
    hardware/src/gpiotester.cpp \
    hardware/src/gpio.cpp \
    testsuite/src/tester.cpp \
    testsuite/src/testcasesourceboardbit.cpp \
    testsuite/src/testcasesourceboardcontrol.cpp \
    testsuite/src/testcasesourceboarddockctrl.cpp \
    testsuite/src/testcasesourceboardtamper.cpp \
    hardware/src/sourceboardrfcontrol.cpp \
    testsuite/src/testcasesourceboardsynth.cpp \
    testsuite/src/testcasesourceboarddcpower.cpp \
    testsuite/src/testcasesourceboardddspower.cpp \
    testsuite/src/testcasesourceboardddsfrequency.cpp \
    testjig/src/cablecal.cpp \
    common/src/calibration.cpp \
    gui/src/griddialog.cpp \
    testsuite/src/testcasesourceboardddscalibration.cpp \
    dut/src/sourceboardbit.cpp \
    hardware/src/registeradc.cpp \
    hardware/src/registergpio.cpp \
    testjig/src/testjigfactory.cpp \
    testjig/src/testharness.cpp \
    testsuite/src/testcasesourceboardddscurrent.cpp \
    dut/src/ddscalfile.cpp \
    gui/src/delayprogressdialog.cpp \
    testsuite/src/testcasepowermonitor.cpp \
    dut/src/powermonitor.cpp \
    testjig/src/testharnesssourceboard.cpp \
    testjig/src/testharnesspowermonitor.cpp \
    testsuite/src/testcasepowermonitordcpower.cpp \
    testsuite/src/testcasepowermonitorinsertionloss.cpp \
    testjig/src/rfpath.cpp \
    gui/src/modaldialog.cpp \
    testsuite/src/testcasepowermonitornorf.cpp \
    testsuite/src/testcasepowermonitordirectivity.cpp \
    hardware/src/rfband.cpp \
    testjig/src/testharnessmembrane.cpp \
    testsuite/src/testcasesourceboardpactrlmonitor.cpp \
    testsuite/src/testcasesourceboarddaughter.cpp \
    testsuite/src/testcasemidbandsourcemodule.cpp \
    testsuite/src/testcasemidbandsourcemoduleid.cpp \
    testsuite/src/testcasemidbandsourcemoduleportsel.cpp \
    testsuite/src/testcasemidbandsourcemoduleatt.cpp \
    testsuite/src/testcasemidbandsourcemodulerfpath.cpp \
    testsuite/src/testcasemidbandsourcemoduledcpower.cpp \
    testsuite/src/testcasemidbandsourcemoduleassy.cpp \
    gui/src/cablecaldialog.cpp \
    common/src/calibrationstatus.cpp \
    gui/src/testjigtreewidgetitem.cpp \
    dut/src/psumodule.cpp \
    testsuite/src/testcasepsumodule.cpp \
    testsuite/src/testcasepsumoduleprogmicro.cpp \
    testsuite/src/testcasepsumodulecontrolport.cpp \
    testsuite/src/testcasepsumoduledcoutput.cpp \
    testsuite/src/testcasepsumodulebit.cpp \
    testsuite/src/testcasepsumodulethermalsensors.cpp \
    testsuite/src/testcasepsumodulefans.cpp \
    testsuite/src/testcasepsumodulepacontrol.cpp \
    dut/src/dockcontroller.cpp \
    testjig/src/testharnesspsumodule.cpp \
    testjig/src/testharnessdockcontroller.cpp \
    testsuite/src/testcasedockcontroller.cpp \
    testsuite/src/testcasepsumoduledcinput.cpp \
    testsuite/src/testcasedockcontrollerprogfpga.cpp \
    testsuite/src/testcasedockcontrollerdcpower.cpp \
    testsuite/src/testcasedockcontrollerbit.cpp \
    testsuite/src/testcasedockcontrollercontrolport.cpp \
    testsuite/src/testcasedockcontrollerpactrlmonitor.cpp \
    testsuite/src/testcasedockcontrollergps.cpp \
    comms/src/psucomms.cpp \
    testsuite/src/testcasesourceboardfileloader.cpp \
    testsuite/src/testcasesourceboardflashbootloader.cpp \
    hardware/src/flashmagic.cpp \
    comms/xmodem/src/xmodem.c \
    comms/xmodem/src/xmodemwrapper.cpp \
    comms/xmodem/src/crc16.c \
    gui/src/fileselectdialog.cpp \
    comms/src/dockcontrollercomms.cpp \
    hardware/src/pacontrolmonitor.cpp \
    testjig/src/pacontrolmonitortest.cpp \
    testsuite/src/testcasedockcontrollereeprom.cpp \
    testsuite/src/testcasedockcontrollerinterfaceid.cpp \
    testsuite/src/testcasesourceboardappboot.cpp \
    hardware/src/powermonitoradc.cpp \
    dut/src/daughtermodule.cpp \
    hardware/src/jlink.cpp \
    testsuite/src/testcasesourceboardflashapp.cpp \
    testsuite/src/testcasesourceboardstoreDdsfile.cpp \
    gui/src/sanitycheckdialog.cpp \
    testjig/src/sanitycheckcal.cpp \
    testsuite/src/testcasesourceboardddscalcheck.cpp \
    common/src/assyrevision.cpp \
    dut/src/ctsboard.cpp \
    testjig/src/testharnessctsboard.cpp \
    testsuite/src/testcasectsboard.cpp \
    testsuite/src/testcasectsboardflashfirmware.cpp \
    testsuite/src/testcasectsboarddcpower.cpp \
    comms/src/ctsboardcomms.cpp \
    testsuite/src/testcasectsboardbit.cpp \
    testsuite/src/testcasectsboardtamper.cpp \
    testsuite/src/testcasectsboardsetserialnumber.cpp \
    testsuite/src/testcasectsboardpreselectorbandwidth.cpp \
    testsuite/src/testcasectsboardifbandwidth.cpp \
    testsuite/src/ctstestband.cpp \
    testsuite/src/testcasectsboardrfbandwidth.cpp \
    testsuite/src/testcasectsboarddynamicrange.cpp \
    testsuite/src/testcasectsboardbatterycharger.cpp \
    testsuite/src/testcasectsboardusbserialport.cpp \
    testsuite/src/testcasectsboardmembraneinterface.cpp \
    testsuite/src/testcasectsboardgetversion.cpp

INCLUDEPATH += gui/inc testequipment/inc common/inc comms/inc comms/xmodem/inc testjig/inc testsuite/inc dut/inc hardware/inc

win32: INCLUDEPATH += "C:\Program Files (x86)\IVI Foundation\VISA\WinNT\include"
win32: LIBS += -Lc:/PROGRA~2/IVIFOU~1/VISA/WinNT/lib/msc -lvisa32

# install
target.path = $$[QT_INSTALL_EXAMPLES]/$${TARGET}
INSTALLS += target

RESOURCES += \
    mercurytestutility.qrc
